n_way: 10
k_shot: 5

use_gpu: true

data:
  train_path: "data/omniglot/images_background"
  test_path: "data/omniglot/images_evaluation"

  augment_rotate: false

model:
  _target_:  models.debug_model.DebugModel
  input_dim: [28, 28, 3]
  num_classes: ${n_way}

trainer:
  train_episodes: 100
  eval_episodes: 100
  eval_every: 10
  
  lr_decay: false
  lr_decay_rate: 0.5
  lr_decay_every: 2000 

  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-3