n_way: 5
k_shot: 5

use_gpu: false

data:
  train_path: "data/omniglot/images_background"
  test_path: "data/omniglot/images_evaluation"

  augment_rotate: false

model:
  _target_: models.matching_network.MatchingNet
  input_dim: [28, 28, 3]
  conv_channels: 64
  num_conv_layers: 4

trainer:
  train_episodes: 100000
  eval_episodes: 1000
  eval_every: 100

  lr_decay: false
  lr_decay_rate: 0.5
  lr_decay_every: 500

  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-3
